Kc34251/setup review
NxFerrara/NFC_Tracking pull request #24
Opened 2024-03-04 23:03 UTC by kc34251

## Changes:
- Changed location and name of script_config file to paths, added color formatting, fixed overall code format. 

## Considerations:
- Needs a final review

2024-03-05 03:07 UTC, jbesoto requested changes
Please fix minor issues.

2024-03-05 03:07 UTC, jbesoto commented on scripts/run/detect_display_errors.sh
> +    if echo "$line" | grep -q -E "${DISPLAY_ERROR_MESSAGE}"; then
Add curly braces for consistency.
```diff
- if echo "$line" | grep -q -E "${DISPLAY_ERROR_MESSAGE}"; then
+ if echo "${line}" | grep -q -E "${DISPLAY_ERROR_MESSAGE}"; then
```

2024-03-05 03:07 UTC, jbesoto commented on scripts/run/init_display.sh
> +    echo "WARNING: ${DISPLAY_FRAME_BUFFER_PATH} does not exist."
Does not follow status message formatting.

2024-03-05 03:07 UTC, jbesoto commented on scripts/setup/setup.sh
These globals are not visible to child processes unless they are exported. For instance, 
```diff
+ export RED GREEN YELLOW BLUE MAGENTA CYAN WHITE BOLD RESET
```

2024-03-05 03:07 UTC, jbesoto commented on scripts/setup/setup.sh
> +OK_MSG="${GREEN}[OK]     ${RESET}"
For consistency, lets change the name of these variables to:
```diff
- OK_MSG="${GREEN}[OK] ${RESET}"
- WARNING_MSG="${YELLOW}[WARNING]${RESET}"
- FAIL_MSG="${RED}[FAIL]   ${RESET}"
+ OK="${GREEN}[OK] ${RESET}"
+ WARNING="${YELLOW}[WARNING]${RESET}"
+ FAIL="${RED}[FAIL]   ${RESET}"
```
Fix all references

2024-03-05 03:07 UTC, jbesoto commented on scripts/run/detect_display_errors.sh
This file has places where variable substitution is not wrapped with curly braces. Please fix.

2024-03-05 15:13 UTC, NxFerrara requested changes
Overall great work. Minor fixes.

2024-03-05 15:13 UTC, NxFerrara commented on scripts/run/detect_display_errors.sh
>          new_error_timestamp=$(echo "$line" | grep -oP '\[\s*\K\d+\.\d+')
Add curly braces here.

2024-03-05 15:13 UTC, NxFerrara commented on scripts/run/detect_display_errors.sh
>          if (( $(echo "$new_error_timestamp > $last_error_timestamp" | bc -l) )); then
Add curly braces here.

2024-03-05 17:42 UTC, jbesoto commented on scripts/run/detect_display_errors.sh
>          new_error_timestamp=$(echo "$line" | grep -oP '\[\s*\K\d+\.\d+')
Duplicate observation. Removing

2024-03-06 17:35 UTC, NxFerrara approved these changes
Looks good.

2024-03-06 17:41 UTC, jbesoto approved these changes
Good job.  Keep it up

2024-03-06 18:15 UTC, merged